"""empty message

Revision ID: 10c2be5357c
Revises: 43e6f6be31c0
Create Date: 2015-06-17 19:08:32.515741

"""

# revision identifiers, used by Alembic.
revision = '10c2be5357c'
down_revision = '43e6f6be31c0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competition', sa.Column('is_review', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competition', 'is_review')
    ### end Alembic commands ###
