"""update

Revision ID: 157ad01d2389
Revises: 272f42723ea0
Create Date: 2015-06-06 16:54:06.061728

"""

# revision identifiers, used by Alembic.
revision = '157ad01d2389'
down_revision = '272f42723ea0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
