"""Integer

Revision ID: 1738c274fc52
Revises: 2c68d33b3345
Create Date: 2015-05-22 11:45:23.427977

"""

# revision identifiers, used by Alembic.
revision = '1738c274fc52'
down_revision = '2c68d33b3345'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
