"""add project data to json

Revision ID: 1f42b7429378
Revises: 44c961ab884a
Create Date: 2015-05-11 12:51:07.572952

"""

# revision identifiers, used by Alembic.
revision = '1f42b7429378'
down_revision = '44c961ab884a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
