"""update

Revision ID: 272f42723ea0
Revises: 329a04e05197
Create Date: 2015-05-23 07:54:37.386033

"""

# revision identifiers, used by Alembic.
revision = '272f42723ea0'
down_revision = '329a04e05197'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
