"""empty message

Revision ID: 280ad518955f
Revises: 3e0fedd10550
Create Date: 2015-06-21 18:26:51.531096

"""

# revision identifiers, used by Alembic.
revision = '280ad518955f'
down_revision = '3e0fedd10550'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competition', sa.Column('date_created', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False))
    op.create_index(op.f('ix_competition_date_created'), 'competition', ['date_created'], unique=False)
    op.add_column('grade', sa.Column('date_created', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False))
    op.create_index(op.f('ix_grade_date_created'), 'grade', ['date_created'], unique=False)
    op.add_column('major', sa.Column('date_created', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False))
    op.create_index(op.f('ix_major_date_created'), 'major', ['date_created'], unique=False)
    op.add_column('participant', sa.Column('date_created', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False))
    op.create_index(op.f('ix_participant_date_created'), 'participant', ['date_created'], unique=False)
    op.add_column('project', sa.Column('date_created', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False))
    op.create_index(op.f('ix_project_date_created'), 'project', ['date_created'], unique=False)
    op.add_column('unit', sa.Column('date_created', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False))
    op.create_index(op.f('ix_unit_date_created'), 'unit', ['date_created'], unique=False)
    op.add_column('user', sa.Column('date_created', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False))
    op.create_index(op.f('ix_user_date_created'), 'user', ['date_created'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_date_created'), table_name='user')
    op.drop_column('user', 'date_created')
    op.drop_index(op.f('ix_unit_date_created'), table_name='unit')
    op.drop_column('unit', 'date_created')
    op.drop_index(op.f('ix_project_date_created'), table_name='project')
    op.drop_column('project', 'date_created')
    op.drop_index(op.f('ix_participant_date_created'), table_name='participant')
    op.drop_column('participant', 'date_created')
    op.drop_index(op.f('ix_major_date_created'), table_name='major')
    op.drop_column('major', 'date_created')
    op.drop_index(op.f('ix_grade_date_created'), table_name='grade')
    op.drop_column('grade', 'date_created')
    op.drop_index(op.f('ix_competition_date_created'), table_name='competition')
    op.drop_column('competition', 'date_created')
    ### end Alembic commands ###
