"""unit_id update

Revision ID: 2f8630a6f269
Revises: 3032de5be566
Create Date: 2015-05-22 11:03:46.204725

"""

# revision identifiers, used by Alembic.
revision = '2f8630a6f269'
down_revision = '3032de5be566'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
