"""update unit.unit_id datatype

Revision ID: 3032de5be566
Revises: b43ed762656
Create Date: 2015-05-21 17:28:09.907894

"""

# revision identifiers, used by Alembic.
revision = '3032de5be566'
down_revision = 'b43ed762656'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
