"""init

Revision ID: 30b77cfe8974
Revises: None
Create Date: 2015-05-04 20:45:59.993791

"""

# revision identifiers, used by Alembic.
revision = '30b77cfe8974'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
