"""Integer to String

Revision ID: 31bbb698fa15
Revises: 1738c274fc52
Create Date: 2015-05-22 11:47:12.560304

"""

# revision identifiers, used by Alembic.
revision = '31bbb698fa15'
down_revision = '1738c274fc52'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
