"""update

Revision ID: 329a04e05197
Revises: 9e355e1b3bb
Create Date: 2015-05-22 12:53:10.028145

"""

# revision identifiers, used by Alembic.
revision = '329a04e05197'
down_revision = '9e355e1b3bb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
