"""update

Revision ID: 344da1ecfa1d
Revises: 4544b53a09b5
Create Date: 2015-06-06 17:56:38.673749

"""

# revision identifiers, used by Alembic.
revision = '344da1ecfa1d'
down_revision = '4544b53a09b5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unit_unit_id', table_name='unit')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_unit_unit_id', 'unit', ['unit_id'], unique=False)
    ### end Alembic commands ###
