"""Integer to String

Revision ID: 3744d69dc02f
Revises: 31bbb698fa15
Create Date: 2015-05-22 12:35:47.785624

"""

# revision identifiers, used by Alembic.
revision = '3744d69dc02f'
down_revision = '31bbb698fa15'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
