"""empty message

Revision ID: 3e0fedd10550
Revises: 10c2be5357c
Create Date: 2015-06-18 03:41:56.043594

"""

# revision identifiers, used by Alembic.
revision = '3e0fedd10550'
down_revision = '10c2be5357c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
