"""update

Revision ID: 414184b0778e
Revises: 344da1ecfa1d
Create Date: 2015-06-06 21:42:32.980127

"""

# revision identifiers, used by Alembic.
revision = '414184b0778e'
down_revision = '344da1ecfa1d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('competitionproject')
    op.add_column('competition', sa.Column('id_project', sa.Integer(), nullable=True))
    op.drop_constraint(u'competition_ibfk_1', 'competition', type_='foreignkey')
    op.create_foreign_key(None, 'competition', 'project', ['id_project'], ['id'])
    op.drop_column('competition', 'id_competitionproject')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competition', sa.Column('id_competitionproject', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'competition', type_='foreignkey')
    op.create_foreign_key(u'competition_ibfk_1', 'competition', 'competitionproject', ['id_competitionproject'], ['id'])
    op.drop_column('competition', 'id_project')
    op.create_table('competitionproject',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('project_name', mysql.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('project')
    ### end Alembic commands ###
