"""update

Revision ID: 4544b53a09b5
Revises: 157ad01d2389
Create Date: 2015-06-06 17:49:55.595815

"""

# revision identifiers, used by Alembic.
revision = '4544b53a09b5'
down_revision = '157ad01d2389'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_unit_unit_id'), 'unit', ['unit_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unit_unit_id'), table_name='unit')
    ### end Alembic commands ###
