"""empty message

Revision ID: 4610e29eb91
Revises: None
Create Date: 2015-06-12 21:50:56.947346

"""

# revision identifiers, used by Alembic.
revision = '4610e29eb91'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
