"""update unit & major

Revision ID: 57de81568393
Revises: 4012a88d7f1
Create Date: 2015-05-21 16:24:39.233156

"""

# revision identifiers, used by Alembic.
revision = '57de81568393'
down_revision = '4012a88d7f1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
