"""update

Revision ID: 57f0a54a06b7
Revises: None
Create Date: 2015-06-09 14:40:33.638771

"""

# revision identifiers, used by Alembic.
revision = '57f0a54a06b7'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=64), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('unit_name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade_name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grade_name')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=128), nullable=False),
    sa.Column('nick_name', sa.String(length=128), nullable=False),
    sa.Column('user_password_hash', sa.String(length=128), nullable=False),
    sa.Column('id_unit', sa.Integer(), nullable=True),
    sa.Column('id_role', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_role'], ['role.id'], ),
    sa.ForeignKeyConstraint(['id_unit'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('major',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('major_id', sa.String(length=128), nullable=True),
    sa.Column('major_name', sa.String(length=128), nullable=True),
    sa.Column('id_acachemy', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_acachemy'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('major_id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=128), nullable=False),
    sa.Column('student_name', sa.String(length=128), nullable=False),
    sa.Column('id_grade', sa.Integer(), nullable=True),
    sa.Column('id_acachemy', sa.Integer(), nullable=True),
    sa.Column('id_major', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_acachemy'], ['unit.id'], ),
    sa.ForeignKeyConstraint(['id_grade'], ['grade.id'], ),
    sa.ForeignKeyConstraint(['id_major'], ['major.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_student_1', sa.Integer(), nullable=False),
    sa.Column('id_student_2', sa.Integer(), nullable=True),
    sa.Column('id_student_3', sa.Integer(), nullable=True),
    sa.Column('id_student_4', sa.Integer(), nullable=True),
    sa.Column('id_student_5', sa.Integer(), nullable=True),
    sa.Column('id_student_6', sa.Integer(), nullable=True),
    sa.Column('id_student_7', sa.Integer(), nullable=True),
    sa.Column('id_student_8', sa.Integer(), nullable=True),
    sa.Column('id_student_9', sa.Integer(), nullable=True),
    sa.Column('id_student_10', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_student_1'], ['student.id'], ),
    sa.ForeignKeyConstraint(['id_student_10'], ['student.id'], ),
    sa.ForeignKeyConstraint(['id_student_2'], ['student.id'], ),
    sa.ForeignKeyConstraint(['id_student_3'], ['student.id'], ),
    sa.ForeignKeyConstraint(['id_student_4'], ['student.id'], ),
    sa.ForeignKeyConstraint(['id_student_5'], ['student.id'], ),
    sa.ForeignKeyConstraint(['id_student_6'], ['student.id'], ),
    sa.ForeignKeyConstraint(['id_student_7'], ['student.id'], ),
    sa.ForeignKeyConstraint(['id_student_8'], ['student.id'], ),
    sa.ForeignKeyConstraint(['id_student_9'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_project', sa.Integer(), nullable=True),
    sa.Column('achievement_name', sa.String(length=128), nullable=True),
    sa.Column('winning_level', sa.String(length=128), nullable=True),
    sa.Column('rate', sa.String(length=128), nullable=True),
    sa.Column('awards_unit', sa.String(length=128), nullable=True),
    sa.Column('winning_time', sa.Date(), nullable=True),
    sa.Column('id_student', sa.Integer(), nullable=True),
    sa.Column('id_participants', sa.Integer(), nullable=True),
    sa.Column('id_teacher_1', sa.Integer(), nullable=True),
    sa.Column('id_teacher_2', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_participants'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['id_project'], ['project.id'], ),
    sa.ForeignKeyConstraint(['id_student'], ['student.id'], ),
    sa.ForeignKeyConstraint(['id_teacher_1'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id_teacher_2'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('competition')
    op.drop_table('participants')
    op.drop_table('student')
    op.drop_table('major')
    op.drop_table('user')
    op.drop_table('project')
    op.drop_table('grade')
    op.drop_table('unit')
    op.drop_table('role')
    ### end Alembic commands ###
