"""update

Revision ID: 58f1ecb4c6a9
Revises: 30b77cfe8974
Create Date: 2015-05-04 20:59:03.250282

"""

# revision identifiers, used by Alembic.
revision = '58f1ecb4c6a9'
down_revision = '30b77cfe8974'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
