"""empty message

Revision ID: 597b4eb06238
Revises: None
Create Date: 2015-06-23 16:39:23.485606

"""

# revision identifiers, used by Alembic.
revision = '597b4eb06238'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('competition', 'date_created',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text(u'CURRENT_TIMESTAMP'))
    op.alter_column('major', 'date_created',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text(u'CURRENT_TIMESTAMP'))
    op.alter_column('participant', 'date_created',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text(u'CURRENT_TIMESTAMP'))
    op.alter_column('project', 'date_created',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text(u'CURRENT_TIMESTAMP'))
    op.alter_column('unit', 'date_created',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text(u'CURRENT_TIMESTAMP'))
    op.alter_column('user', 'date_created',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text(u'CURRENT_TIMESTAMP'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'date_created',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text(u'CURRENT_TIMESTAMP'))
    op.alter_column('unit', 'date_created',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text(u'CURRENT_TIMESTAMP'))
    op.alter_column('project', 'date_created',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text(u'CURRENT_TIMESTAMP'))
    op.alter_column('participant', 'date_created',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text(u'CURRENT_TIMESTAMP'))
    op.alter_column('major', 'date_created',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text(u'CURRENT_TIMESTAMP'))
    op.alter_column('competition', 'date_created',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text(u'CURRENT_TIMESTAMP'))
    ### end Alembic commands ###
