"""initial migration

Revision ID: 8854e3056ef
Revises: None
Create Date: 2015-04-28 20:42:59.644190

"""

# revision identifiers, used by Alembic.
revision = '8854e3056ef'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
