"""update

Revision ID: 9e355e1b3bb
Revises: 4ff862cb66a8
Create Date: 2015-05-22 12:44:25.760639

"""

# revision identifiers, used by Alembic.
revision = '9e355e1b3bb'
down_revision = '4ff862cb66a8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
