"""update major.major_id datatype

Revision ID: b43ed762656
Revises: 57de81568393
Create Date: 2015-05-21 17:26:36.585492

"""

# revision identifiers, used by Alembic.
revision = 'b43ed762656'
down_revision = '57de81568393'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
